5.3 Преобразования функций Сдвиги вправо и влево.ipynb

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sympy import *
from sympy.plotting import plot
from sympy.plotting import plot3d
from sympy import solve_univariate_inequality

init_printing(use_unicode=False, wrap_line=False, no_global=True)

In [ ]:
def print_points_ands_function(sympy_function):
    def function(x_): return float(sympy_function.subs(x, x_))
    
    points_X = np.array([-5, -4, -3, -2, -1, 1, 2, 3, 4, 5])
    points_Y = np.array([23, 19, 5, 7, 3, 2, 9, 19, 8, 22])
    plt.xlim(-15, 15)
    plt.ylim(-5, 40)
    
    plt.scatter(points_X, points_Y, c='r')
    x_range = np.linspace(plt.xlim()[0], plt.xlim()[1], num=100)
    function_Y = [function(x_) for x_ in x_range]
    plt.plot(x_range, function_Y, 'b')
    plt.show()
    
    MSE = sum([(points_Y[i] - function(points_X[i]))**2 for i in range(len(points_Y))]) / len(points_Y)
    print(f'MSE = {MSE}')

In [ ]:
x = Symbol("x")

f = x**2 / 3
print(f"original: {f}")
print_points_ands_function(f)

In [ ]:
f_new = f.subs(x, x*1.9)
print(f_new)
print_points_ands_function(f_new)

In [ ]:
f2 = f * 3
print_points_ands_function(f2)

In [ ]:
# поиск производной функции f(x) = kx + b при k = 0.5
# answer: 2b - 10/3
# 2b - 10/3 > 0 => 2b > 10/3 => b > 5/3 (divided 2b & 10/3 on 2)
# 2b - 10/3 < 0 => b < 5/3
# 2b - 10/3 = 0 => b = 5/3

In [ ]:
x, y, z = symbols("x, y, z")

f = 0.8*x + 20*y
plot3d(f)

In [ ]:
f1 = x*y / sqrt(x**2 + y**2 - 5)
f1

In [ ]:
plot3d(f1)

In [ ]:
from random import randint


f = 5*x - 3*y + 2
print(pretty(solve(f), use_unicode=1))
# 5x - 3y + 2 = 0
# 5x = 3y - 2 / 5
# x = 3/5y - 2/5
some_y = randint(0, 9)
some_x = 3/5 * some_y - 2/5
print(f"x={some_x}, y={some_y}")
print(5* some_x - 3*some_y + 2)

In [ ]:
a1, a2 = symbols("a1, a2")
MSE = 1/4 * (
    (a1*1 + a2*2 - 5)**2 + 
    (a1*5 + a2*3 - 6)**2 +
    (a1*2 + a2*4 - 10)**2 +
    (a1*3 + a2*7 - 8)**2
             )
# поиск производных для MSE(a1) и MSE(a2)
gradMSEa1 = diff(MSE, a1)
gradMSEa2 = diff(MSE, a2)
print("a1: " + pretty(gradMSEa1))
print("a2: " + pretty(gradMSEa2))

print(f"point a1: {gradMSEa1.subs({a1: 0.395, a2: 0.62})}")
print(f"point a2: {gradMSEa2.subs({a1: 0.395, a2: 0.62})}")


# MSE.subs([(a1, 0.5), (a2, 1.3)]) or
MSE.subs({a1: 0.5, a2: 1.3})



In [ ]:
x, y, z = symbols("x, y, z")

MSE = 1/6 * ((5*x + 7*y - 5*z + 47)**2 +
             (-2*y - 2*z - 10)**2 +
             (-4*x - 8*y - 7*z - 63)**2 +
             (x + y + 2*z + 1)**2 +
             (2*x - y + 2*z + 4)**2 +
             (4*x + y + 4*z + 2)**2)
# значение ошибки в точке [0,0,0]
startMSEvalue = MSE.subs({x: 0, y: 0, z: 0})
print(startMSEvalue)

# вычисляем частные производные
MSEx = diff(MSE, x)
MSEy = diff(MSE, y)
MSEz = diff(MSE, z)
print(f"MSEx: {pretty(MSEx)}\nMSEy: {pretty(MSEy)}\nMSEz: {pretty(MSEz)}")

# задаем шаг 
step = 0.01
# начальная точка
startPoint = np.array([0, 0, 0])
lastMSEvalue = startMSEvalue
count = 0

while(lastMSEvalue > 55):
    # задаем градиент и вычисляем начальную точку
    grad = np.array([MSEx.subs({x: startPoint[0], y: startPoint[1], z: startPoint[2]}), 
                    MSEy.subs({x: startPoint[0], y: startPoint[1], z: startPoint[2]}), 
                    MSEz.subs({x: startPoint[0], y: startPoint[1], z: startPoint[2]})])
    # значения градиента начальной точки
    print(grad)

    # делаем 1 шаг по градиентому спуску
    nextPoint = startPoint - step  * grad
    print(f"one step by grad:\n{nextPoint}")
    startPoint = nextPoint

    # вычисляем значение ошибки
    lastMSEvalue = MSE.subs({x: nextPoint[0], y: nextPoint[1], z: nextPoint[2]})
    print(lastMSEvalue)
    count +=1

print(count)
print(lastMSEvalue)

In [ ]:
A1 = np.array([[1, -5, 3],[7.5, -12.5, 6]])
A2 = np.array([[1, 2],[3, 4],[5, 6]])
np.matmul(A2, A1)

A1 = np.array([[5, 5],[7, 8]])
A2 = np.array([[1, 2],[3, 4]])
print(np.matmul(A1, A2))
print(np.matmul(A2, A1))


# нахождение определителя матрицы
X = np.array([[6, 5, 7],[6, 3, 4],[5, -2, -3]])
print(X)
np.linalg.det(X)

In [294]:
X = np.array([[5.0, 7.0, -5.0],
             [0.0, -2.0, 2.0],
             [-4.0, -8.0, -7.0],
             [1.0, 1.0, 2.0],
             [2.0, -1.0, 2.0],
             [4.0, 1.0, 4.0]])
print(pretty(X))
b = np.array([-47.0, 10.0, 63.0, -1.0, -4.0, -2.0])

# (X.T * X)**-1 * X.T
mul = np.matmul(X.T, X)
print(mul)
# np.linalg.det(mul)

(X.T @ X)**-1 @ X.T * b

 [[ 5.  7. -5.]
  [ 0. -2.  2.]
  [-4. -8. -7.]
  [ 1.  1.  2.]
  [ 2. -1.  2.]
 [ 4.  1.  4.]]
[[ 62.  70.  25.]
 [ 70. 120.  21.]
 [ 25.  21. 102.]]


array([[  0.90967742,   0.51428571, -28.90451613,  -0.11041475,
         -0.3918894 ,  -0.47760369],
       [  5.09166667,   0.78571429, -28.8       ,  -0.11785714,
         -0.46190476,  -0.51190476],
       [-22.7627451 ,  -0.75630252, -38.40352941,  -0.10722689,
         -0.20795518,  -0.49366947]])